class Box{
    constructor(container,width,height,x,y,velX,velY,bgcolor,text){
        this.div;
        this.container=container;
        this.width=width;
        this.height=height;
        this.x=x;
        this.y=y;
        this.velX=velX;
        this.velY=velY;
        this.bgcolor=bgcolor;
        this.text=text;
        this.div=document.createElement("div");
        this.div.style.width=this.width+"px";
        this.div.style.height=this.height+"px";
        this.div.style.position="absolute";
        this.div.style.left=this.x+"px";
        this.div.style.top=this.y+"px";
        this.div.style.textAlign="center";
        this.div.style.background=this.bgcolor;
        this.div.innerText=this.text;
        this.container.appendChild(this.div);
    }
    tick(){
        this.x=this.x+this.velX;
        this.y=this.y+this.velY;
    }
    render(){
        this.div.style.left=this.x+"px";
        this.div.style.top=this.y+"px"; 
    }
}